### ISSUE TITLE
Terser syntax through well-documented defaults and inference

### ISSUE THREAD

**Issue by jsejcksn** [BentoumiTech/denox#16]
## Issue Type

- Feature Request

It appears that one of the primary goals of this project is to reduce typing. I think every programmer loves that.

It might be possible to allow for even terser syntax by establishing and documenting some sensible defaults and inference behavior. Here are some suggested considerations:

**Default script:**

For example, one could use the command `denox run`, which would be expanded to `denox run default`. (I gave `default` as the example here, but maybe you like `main`, etc.)

Example:

`deno-workspace.yaml`
```yaml
scripts:
  default:
    file: main.ts
    deno_options:
      allow-net: example.com
```

`shell`
```shell
> denox run
# equal to:
# deno run --allow-net=example.com main.ts
```

**Inferring file from script:**

Likewise, in `deno-workspace.scripts`:
If a script does not provide a value for `file`, it could be inferred from its script key—this would allow it to be an optional property if people would like to organize scripts directly by file name. This practice provides the advantage of native terminal tab-completion and also promotes an organizational structure which aligns with the workspace filesystem.

Example:

This:
```yaml
scripts:
  main.ts:
    file: main.ts
    deno_options:
      allow-net: example.com
```

could be equal to:
```yaml
scripts:
  main.ts:
    deno_options:
      allow-net: example.com
```
