### ISSUE TITLE
Add option: args

### ISSUE THREAD

**Issue by jsejcksn** [BentoumiTech/denox#19]
## Issue Type

- Feature Request

Add a new `args` string array property to `workspace.globals` and `workspace.scripts[scriptName]`.

This would allow default arguments to be appended to the interpolated command. Here are some examples:

Script:

```yaml
scripts:
  develop:
    file: main.ts
    args:
      - hello
globals:
  deno_options:
    allow-read: true
```

```shell
> denox run develop
# equal to:
# deno run --allow-read main.ts hello
```

```shell
> denox run develop more args
# equal to:
# deno run --allow-read main.ts hello more args
```

---

Global:

```yaml
scripts:
  develop:
    file: main.ts
globals:
  args:
    - foo bar
    - baz
  deno_options:
    allow-read: true
```

```shell
> denox run develop
# equal to:
# deno run --allow-read main.ts "foo bar" baz
```

```shell
> denox run develop more args
# equal to:
# deno run --allow-read main.ts "foo bar" baz more args
```

---

Both: (script replaces global, like with `deno_options`)

```yaml
scripts:
  develop:
    file: main.ts
    args:
      - nice to
      - meet you
globals:
  args:
    - foo bar
    - baz
  deno_options:
    allow-read: true
```

```shell
> denox run develop
# equal to:
# deno run --allow-read main.ts "nice to" "meet you"
```

```shell
> denox run develop more args
# equal to:
# deno run --allow-read main.ts "nice to" "meet you" more args
```

**Comment by jsejcksn** [comment]
Perhaps the `args` value can also be `null` to handle the case where it is set on `workspace.globals` but one or more scripts shouldn't inherit the value.

**Comment by BentoumiTech** [comment]
@jsejcksn I was thinking of implementing `args` as you are suggesting but then I realized that giving support for inline arbitrary script execution would actually solve this issue while keeping denox public API smaller.

Eg :
```yaml
scripts:
  develop:
    file: main.ts
  develop_with_args:
    cmd: denox run develop hello
globals:
  deno_options:
    allow-read: true
```

```bash
> denox run develop_with_args
# equal to:
# deno run --allow-read main.ts hello
```

```bash
> denox run develop_with_args more args
# equal to:
# deno run --allow-read main.ts hello more args
```

**Comment by jsejcksn** [comment]
> while keeping denox public API smaller

@BentoumiTech Can you explain what you mean by that?

From my current perspective, adding `cmd` instead of `args` actually makes things more complicated. Previously, Denox was simply a Deno script runner. Adding `cmd` fundamentally changes what Denox does.

**Comment by BentoumiTech** [comment]
@jsejcksn I see your point.

Adding `cmd` I think is more flexible. I had many times in different project added for example a clean command that would do `rm -Rf build/` in denox that would look like this : 

```
scripts:
  clean:
    cmd: rm -Rf build
```
`denox run clean`

> while keeping denox public API smaller

I meant that with `cmd` user would be able to achieve almost everything that would be possible with `args` without adding a new property.

**Comment by jsejcksn** [comment]
I'm not sure that I agree about using the word "flexible". I agree that it can be "convenient".

---

The current equivalent of your example:

`clean.ts`:
```ts
Deno.run({ cmd: ['rm', '-Rf', 'build'] });
```

`deno-workspace.yaml`:
```yaml
scripts:
  clean:
    file: clean.ts
    deno_options:
      allow-run: true
```

---

Not quite as convenient to type as your example, but it allows for extending functionality and can handle cross-platform discrepancies. The example command `rm -Rf build` will simply fail in Windows command prompt, but can be handled in the Deno script:

`clean.ts`:
```ts
if (Deno.build.os === 'windows') {
  Deno.run({ cmd: ['rd', '/s', '/q', 'build'] });
}
else {
  Deno.run({ cmd: ['rm', '-Rf', 'build'] });
}
```

Implementing `cmd` changes Denox from "a cross platform script runner and workspace wrapper for Deno" to "a cross platform script runner and workspace wrapper for Deno, and **a platform/environment-dependent** script runner".

I am not saying that I'm necessarily against the `cmd` idea compared to `args`, but this is one of many things that needs to be considered about `cmd` before implementing it.
