### ISSUE TITLE
deno_options: config spacer issue

### ISSUE THREAD

**Issue by yihua1218** [BentoumiTech/denox#8]
## Issue Type

- [x] Bug Report
- [ ] Feature Request
- [ ] Other

## Expected

> src/tsconfig.app.json

```json
{
  "compilerOptions": {
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true
  }
}
```

> deno-workspace.yml

```yaml
scripts:
  # deno run --allow-net --allow-read --config ./src/tsconfig.app.json app.ts
  # deno run --allow-net --allow-read --config=./src/tsconfig.app.json app.ts
  start:
    file: app.ts
    deno_options:
      allow-net: true
      allow-read: true
      config: ./src/tsconfig.app.json
  develop:
    file: main.ts
  globals:
    deno_options:
      allow-read: true
```

Expected to execute like: deno run --allow-net --allow-read --config ./src/tsconfig.app.json app.ts

```bash
> denox run start
Compile https://deno.land/std@0.50.0/fmt/colors.ts
register Controller:  HomeController
register route:  /home/text
register route:  /home/json
Server start in :8000
```

## Actual

Actual to execute like: deno run --allow-net --allow-read "--config ./src/tsconfig.app.json" app.ts

```bash
> denox run start
error: Found argument '--config ./src/tsconfig.app.json' which wasn't expected, or isn't valid in this context
        Did you mean --config?

USAGE:
    deno run <SCRIPT_ARG>... --allow-net=<allow-net> --allow-read=<allow-read> --config <FILE>

For more information try --help
```

## Possible Solutions

I tried to revise the spacer of the config from " " to "=", it seems could be a workaround. I tested it, it seems working fine. But I am not sure is there is another way to let the --config argument not to combine with --config as a string.

https://github.com/yihua1218/denox/commit/c9e36860f16ceb5331d7ab95a7c801a9144cdb4c

## Info

- DenoX version: denox/0.3.0 darwin-x86_64 deno-1.0.0
